const assert = require('node:assert/strict');
const { randomBytes } = require('node:crypto');
process.env.STRIPE_SECRET_KEY = 'sk_test_placeholder';
process.env.STRIPE_PUBLISHABLE_KEY = 'pk_test_placeholder';
process.env.ADMIN_PASSWORD = randomBytes(20).toString('hex');
process.env.ADMIN_SESSION_SECRET = randomBytes(40).toString('hex');
process.env.SITE_URL = 'https://www.moin-flinka.de';
const stripe = require('../api/_lib/stripe-client');
const prices = require('../plate-prices.json');
const body = { orderType: 'plate', city: 'HH', letters: 'MF', digits: '123', name: 'Testkunde', phone: '+49123456789', email: 'test@example.com', street: 'Teststraße 1', postcode: '20095', town: 'Hamburg', privacy: 'on', plateType: 'normal', plateVariant: 'standard', season: false, carbon: false, environmentSticker: false, quantity: 2, delivery: 'standard', basePriceCents: prices.pair, extrasPriceCents: 0, deliveryPriceCents: prices.standard, totalPriceCents: prices.pair + prices.standard };
const session = { id: 'cs_test_order', created: 1700000000, amount_total: 2490, currency: 'eur', payment_status: 'paid', metadata: { ...body, quantity: '2' } };
let created, updated, promotion;
stripe.taxRates.list = async () => ({ data: [{ id: 'txr_test', inclusive: true, percentage: 19, country: 'DE' }] });
stripe.customers.create = async () => ({ id: 'cus_test' });
stripe.checkout.sessions.create = async options => { created = options; return { client_secret: 'test_secret' }; };
stripe.checkout.sessions.list = async () => ({ data: [session, { ...session, id: 'cs_unpaid', payment_status: 'unpaid' }], has_more: true });
stripe.checkout.sessions.retrieve = async () => session;
stripe.checkout.sessions.update = async (id, value) => { updated = { id, value }; };
stripe.promotionCodes.list = async () => ({ data: [], has_more: false });
stripe.coupons.create = async () => ({ id: 'coupon_test' });
stripe.promotionCodes.create = async value => { promotion = value; };
const checkout = require('../api/create-checkout-session');
const { isCompletedPayment } = require('../api/_lib/plate-order');
const admin = require('../api/admin');
const headers = { origin: process.env.SITE_URL, 'x-forwarded-for': '127.0.0.1' };
async function call(handler, method, body, extra = {}) {
  const result = { headers: {} };
  const response = { setHeader(k, v) { result.headers[k] = v; }, status(code) { result.status = code; return this; }, json(data) { result.body = data; return this; } };
  await handler({ method, body, headers, query: {}, ...extra }, response);
  return result;
}
(async () => {
  assert.equal(isCompletedPayment({ payment_status: 'no_payment_required', status: 'complete' }), true);
  assert.equal(isCompletedPayment({ payment_status: 'no_payment_required', status: 'open' }), false);
  let result = await call(checkout, 'POST', body);
  assert.equal(result.status, 200); assert.equal(created.ui_mode, 'elements'); assert.deepEqual(created.payment_method_types, ['card', 'amazon_pay']); assert.equal(created.success_url, undefined); assert.match(created.return_url, /^https:\/\/www.moin-flinka.de/); assert.equal(result.body.clientSecret, 'test_secret');
  result = await call(checkout, 'POST', { ...body, testMode: true, basePriceCents: 50, deliveryPriceCents: 0, totalPriceCents: 50 }); assert.equal(result.status, 400, 'Public test pricing cannot bypass real prices');
  result = await call(checkout, 'POST', { ...body, discountCode: 'INVALID' }); assert.equal(result.status, 400);
  result = await call(admin, 'GET'); assert.equal(result.status, 401); assert.equal(result.body.orders, undefined);
  result = await call(admin, 'POST', { action: 'login', username: 'wrong', password: process.env.ADMIN_PASSWORD }); assert.equal(result.status, 401);
  result = await call(admin, 'POST', { action: 'login', username: 'admin', password: process.env.ADMIN_PASSWORD }); assert.equal(result.status, 200); assert.match(result.headers['Set-Cookie'], /HttpOnly; Secure; SameSite=Strict/);
  const cookie = result.headers['Set-Cookie'].split(';')[0]; const authenticated = { headers: { ...headers, cookie } };
  result = await call(admin, 'GET', undefined, authenticated); assert.equal(result.body.orders.length, 1); assert.equal(result.body.orders[0].customer.street, body.street); assert.equal(result.body.nextCursor, 'cs_unpaid');
  result = await call(admin, 'GET', undefined, { headers: { ...headers, cookie: cookie + 'tampered' } }); assert.equal(result.status, 401);
  result = await call(admin, 'POST', { action: 'status', id: session.id, status: 'Gedruckt' }, authenticated); assert.equal(result.status, 200); assert.equal(updated.value.metadata.fulfillmentStatus, 'Gedruckt');
  result = await call(admin, 'POST', { action: 'status', id: session.id, status: 'Bad' }, authenticated); assert.equal(result.status, 400);
  result = await call(admin, 'POST', { action: 'status', id: session.id, status: 'Gedruckt' }, { headers: { ...headers, cookie, origin: 'https://evil.example' } }); assert.equal(result.status, 403);
  result = await call(admin, 'POST', { action: 'create-discount', code: 'MOIN10', percent: '10', max: '20' }, authenticated); assert.equal(result.status, 200); assert.equal(promotion.promotion.coupon, 'coupon_test'); assert.equal(promotion.max_redemptions, 20);
  result = await call(admin, 'POST', { action: 'create-discount', code: 'MOIN10', percent: '101' }, authenticated); assert.equal(result.status, 400);
  result = await call(admin, 'POST', { action: 'delete-orders', ids: [session.id] }); assert.equal(result.status, 401);
  result = await call(admin, 'POST', { action: 'delete-orders', ids: [] }, authenticated); assert.equal(result.status, 400);
  result = await call(admin, 'POST', { action: 'delete-orders', ids: Array(101).fill(session.id) }, authenticated); assert.equal(result.status, 400);
  result = await call(admin, 'POST', { action: 'delete-orders', ids: [session.id] }, { headers: { ...headers, cookie, origin: 'https://evil.example' } }); assert.equal(result.status, 403);
  const sessions = new Map([[session.id, session], ['cs_second', { ...session, id: 'cs_second', metadata: { ...session.metadata } }], ['cs_unpaid', { ...session, id: 'cs_unpaid', payment_status: 'unpaid', metadata: { ...session.metadata } }]]);
  const changes = [];
  stripe.checkout.sessions.retrieve = async id => sessions.get(id);
  stripe.checkout.sessions.update = async (id, value) => { changes.push(id); Object.assign(sessions.get(id).metadata, value.metadata); };
  stripe.checkout.sessions.list = async () => ({ data: [...sessions.values()], has_more: false });
  result = await call(admin, 'POST', { action: 'delete-orders', ids: [session.id, 'cs_unpaid'] }, authenticated); assert.equal(result.status, 404); assert.deepEqual(changes, []);
  result = await call(admin, 'POST', { action: 'delete-orders', ids: [session.id, 'cs_second', session.id] }, authenticated); assert.equal(result.status, 200); assert.deepEqual(result.body.deletedIds, [session.id, 'cs_second']); assert.equal(changes.length, 2); assert.equal(session.payment_status, 'paid'); assert.equal(session.metadata.name, body.name);
  result = await call(admin, 'GET', undefined, authenticated); assert.equal(result.body.orders.length, 0);
  result = await call(admin, 'GET', undefined, { ...authenticated, query: { id: session.id } }); assert.equal(result.status, 404);
  result = await call(admin, 'POST', { action: 'status', id: session.id, status: 'Gedruckt' }, authenticated); assert.equal(result.status, 404);
  stripe.checkout.sessions.update = async () => { throw new Error('Temporary Stripe failure'); };
  result = await call(admin, 'POST', { action: 'delete-orders', ids: ['cs_second'] }, authenticated); assert.deepEqual(result.body.failedIds, ['cs_second']); assert.deepEqual(result.body.deletedIds, []);
  for (let i = 0; i < 6; i++) result = await call(admin, 'POST', { action: 'login', username: 'admin', password: 'wrong' }); assert.equal(result.status, 429);
  console.log('PASS: Custom checkout, server pricing, login protection, order data, statuses, CSRF, discounts, single and bulk deletion, login rate limit');
})().catch(e => { console.error(e); process.exitCode = 1; });
